In [4]:
import torchvision
import torch
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

from torch.autograd import Variable
# ================================================================== #
#                         Table of Contents                          #
# ================================================================== #

# 1. Basic autograd example 1               
# 2. Basic autograd example 2               
# 3. Basic autograd example 3               
# 4. Loading data from numpy                
# 5. Input pipline                          
# 6. Input pipline for custom dataset       
# 7. Pretrained model                       
# 8. Save and load model                     

In [6]:
# ================================================================== #
#                     1. Basic autograd example 1                    #
# ================================================================== #

# Create tensors.
x = Variable(torch.ones(2, 2) * 2, requires_grad=True)
z = 2 * (x * x) + 5 * x
z.backward(torch.ones(2, 2))
print(x.grad)

tensor([[13., 13.],
        [13., 13.]])


In [2]:
# ================================================================== #
#                     1. Basic autograd example 2                   #
# ================================================================== #

# Create tensors.
'''
torch.Tensor is an alias for the default tensor type (torch.FloatTensor).
requires_grad indicates whether a variable is trainable. By default, requires_grad is False in creating a Variable. 
refer: https://pytorch.org/docs/stable/tensors.html for more details
'''
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [3]:
# ================================================================== #
#                    2. Basic autograd example 2                     #
# ================================================================== #

# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[ 0.2819, -0.1215, -0.3582],
        [ 0.1451,  0.4165, -0.0893]], requires_grad=True)
b:  Parameter containing:
tensor([-0.5468,  0.0037], requires_grad=True)
loss:  1.047200083732605
dL/dw:  tensor([[ 0.7369, -0.3535,  0.3357],
        [ 0.0359,  0.6369,  0.0041]])
dL/db:  tensor([-0.7183,  0.3187])
loss after 1 step optimization:  1.029280662536621
